# Generated by Django 2.0.4 on 2018-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='datefinish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
