# Generated by Django 2.0.4 on 2018-05-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=70)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('dateadmission', models.DateTimeField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
                ('license', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=70)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('birthday', models.DateTimeField()),
                ('dateadmission', models.DateTimeField()),
                ('phone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=30)),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
