# Generated by Django 2.0.4 on 2018-05-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serialnumber', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('country', models.CharField(max_length=10)),
                ('terminationdate', models.DateTimeField()),
            ],
        ),
    ]
